Bootstrap: docker
From: debian:latest

%labels
    AUTHOR icaoberg, luism
    EMAIL icaoberg@psc.edu, luism@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-lowcharts
    COPYRIGHT Copyright © 2021-2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 0.5.9

%post
    apt update
    apt install -y wget
    wget -nc https://github.com/juan-leon/lowcharts/releases/download/v0.5.8/lowcharts_0.5.9_amd64.deb
    dpkg -i lowcharts_0.5.9_amd64.deb && rm -fv lowcharts_0.5.9_amd64.deb
    apt remove -y wget
    apt clean

%runscript
    lowcharts "$@"
